### ISSUE TITLE
FSEの背景色を変更するにはどうすればよいですか？

### ISSUE THREAD

**Issue by ucandoit74** [bytedesign-net/hariko#2]
暗い背景に明るい文字を書いています。
しかし、FSEの背景は変わりません。

![화면 캡처 2024-05-05 132310](https://github.com/bytedesign-net/hariko/assets/64240170/c8a0eb2b-a604-4ea6-b0f9-ffd5c918236d)

![화면 캡처 2024-05-05 130802](https://github.com/bytedesign-net/hariko/assets/64240170/2b28149b-2caa-4a8e-89d2-6268a843b05c)

どうすればEditorの背景色を変更できますか？

**Comment by bytedesign-net** [comment]
エディター内のスタイルはFSEでは変更できませんのでeditor-style.cssを編集してスタイルを追加してください。

--- editor-style.css ---
```
/* before */
body {
  background-color: var(--wp--preset--color--base-2);
}
```
---
--- editor-style.css ---
```
/* after */
body {
  background-color: #000000;
}
```
---

editor-style.cssはブロックによって反映されない場合があるのでどうしても必要な部分だけの追加をおすすめします。

**Comment by ucandoit74** [comment]
> エディター内のスタイルはFSEでは変更できませんのでeditor-style.cssを編集してスタイルを追加してください。
> 
> --- editor-style.css ---
> 
> ```
> /* before */
> body {
>   background-color: var(--wp--preset--color--base-2);
> }
> ```
> 
> --- editor-style.css ---
> 
> ```
> /* after */
> body {
>   background-color: #000000;
> }
> ```
> 
> editor-style.cssはブロックによって反映されない場合があるのでどうしても必要な部分だけの追加をおすすめします。

정말로 고맙습니다.
本当に ありがとう。
